### PR TITLE
Swik-1636 cookie on all domains bug

### PR DESCRIPTION
**Pull request by TBoonX**
I removed all domain entries inside the userStoragePlugin
Testing is quite hard. I did test it with localhost, thus cookies are working in general but we will see If the issue is fixed

### CODE REVIEW

**Comment by kprist** [comment]
@TBoonX if you want more people to test this, could you list a few steps we could take ?

**Comment by TBoonX** [comment]
To test it properly, you need a domain and a subdomain (where you can run the code) to test the cookie on. Signing in in the domain should create a cookie with the domain as domain value. If there is a leading dot then this fix does not work. After creating the cookie the subdomain should be visited. If there is also a cookie on the subdomain active this fix didnt help. And vice versa.
In the unfixed version of the code the domain value was .domain    -> the leading dot makes the cookie valid for the domain and all its subdomains.

**Comment by kprist** [comment]
@TBoonX maybe then we can test this by putting some domains like you described in my `/etc/hosts` file ?

**Comment by TBoonX** [comment]
@kprist Should work

**Comment by kadevgraaf** [comment]
Thanks!
Looks good when logging in/out between experimental and localhost. 
Can we further test this between experimental.slidewiki.org and testing.slidewiki.org?

**Pull request merged**
