### PR TITLE
Swik 2250   support simple slide transistions

### PR DESCRIPTION
**Pull request by sednanref**
Hi @kadevgraaf , in this PR I added the feature to change different transitions at a slide level, in the end, it was easier than changing the full presentation transitions, the sweet alert hanging around there is to add a future option to change the transitions for the full presentation, but I think this could be tackled in a different task. In order for this code to work, you need to run this deck-service version which has already a PR, it supports transitions in slides: [SWIK-2250 in deck service](https://github.com/slidewiki/deck-service/pull/144)

### CODE REVIEW

**Comment by kprist** [comment]
@sednanref @kadevgraaf can someone resolve the conflicts here ?

**Comment by sednanref** [comment]
@kprist I will :)

**Comment by kprist** [comment]
@sednanref  I've merged the deck service PR for this, please retest this branch with experimental service as well

**Comment by kprist** [comment]
Tested it too, briefly. Works well, but I'm not sure if @abijames needs to check this as well.

**Comment by kadevgraaf** [comment]
Works well for me too 👍  Thanks @sednanref !

**Comment by sednanref** [comment]
@kadevgraaf you are welcome :smile:

**Pull request merged**
