### PR TITLE
SWIK-1539_listed_group_creato

### PR DESCRIPTION
**Pull request by TBoonX**
Added creator of a group as member to member counts and group edit view. Also improved a few texts.
I also assured that the group details modal, could be opened in deck edit view, is rendered correctly by showing it after the data was getted.

### CODE REVIEW

**Comment by abijames** [comment]
This is ok to merge. 

But have one suggestion... you could replace "You are the creator, which makes you also a member" with "Group owner" to make it simpler

**Comment by TBoonX** [comment]
@abijames Which option do you mean/want:
1. "You are the group owner, which makes you also a member"
2. "Group owner"

**Comment by abijames** [comment]
2. Group owner

**Comment by TBoonX** [comment]
I asked because it seems to be very unclear to users that they are the creator and member at once.

**Pull request merged**
