### PR TITLE
SWIK-1692 social share buttons in presentation rooms

### PR DESCRIPTION
**Pull request by rmeissn**
I've implemented social share buttons for presentation rooms. URL sharing has been also moved to this menu. I've tried to add useful aria attributes. Additionally a twitter hashtag button has been added, that uses an autogenerated hashtag.

Is it better to share a link to slidewiki view/edit mode instead of the presentation mode?

Sharing via E-Mail is unfortunately not possible due to a browser bug of chrome (at least I think it is). I've reported this bug at [the chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=804851&q=component%3ABlink%3EWebRTC%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

This PR does not resolve Ticket SWIK-1692. It's just a part of it.

social buttons

### CODE REVIEW

**Comment by rmeissn** [comment]
check

**Comment by rmeissn** [comment]
BTW.: What's the best way to construct room specific hashtags? My current approach: "SW" + deck-id-revision (e.g. SW61)

**Comment by rmeissn** [comment]
I've partly reused the hashtag state property in [this branch](https://github.com/slidewiki/slidewiki-platform/tree/SWIK-1692-twitter-timeline-in-pres-rooms-chat). The hashtag in this branch is already calculated differently - "#SWORG #D6R1" for SlideWiki.org Deck6Revision1. Nevertheless, my question is still relevant.

**Comment by TBoonX** [comment]
Please update again (from master)

**Comment by TBoonX** [comment]
I have no twitter account but an windows opened and showed the twitter site with an example text for a post and with the URL included. A hashtag was missing.
Re Hastags: #SWORG #D6R1 sounds good

**Comment by rmeissn** [comment]
@ali1k Can you please test the social buttons and tweet button? @TBoonX and me do not use Twitter...

**Comment by kadevgraaf** [comment]
screen shot 2018-03-07 at 16 09 14
Works well afaik. 👍

**Comment by rmeissn** [comment]
That should have worked in FF too. Maybe a bug independent of the twitter features.
Can you file a bug report?

**Pull request merged**
