### PR TITLE
Swik 673 update signup form

### PR DESCRIPTION
**Pull request by abijames**
updated sign up form to improve messaging, accessibility & add organisation field.

### CODE REVIEW

**Comment by dpaun** [comment]
For this to work, there should be some small changes in the user-service API. @TBoonX (or someone who has worked on the user-service) needs to make modifications to the '/register' handler, and add the 'organization' parameter.

**Comment by abijames** [comment]
Update to user service is done - SWIK-676

**Comment by kadevgraaf** [comment]
Hi @dpaun , @abijames , and @TBoonX 

Should we merge this in master - and thereby included it in the update to stable.slidewiki.org?

**Comment by abijames** [comment]
@kadevgraaf  let me just remind myself what is on this branch...

**Comment by dpaun** [comment]
I'm not sure. As far as I can see, it is already a part of stable.slidewiki.org, but it is not merged into platform.experimental.slidewiki.org.

**Comment by abijames** [comment]
@dpaun is correct. These changes are already on stable.

**Comment by bwulff** [comment]
This has been merged into branch SWAD-26_release_on_stable. Closing PR since we won't merge this into master as it is an interim solution as long as user groups right management is not in place.

We should keep it as an optional feature though! There may be adopters in the future who want to restrict signup in the way this does (e.g. only to their students)

**Pull request closed without merging**
