### PR TITLE
Swik 1075 redesign history tab

### PR DESCRIPTION
**Pull request by stavmars**
This PR concerns the redesigned history tab which includes a more detailed history through the newly introduced change log.

### CODE REVIEW

**Comment by stavmars** [comment]
This cannot be merged yet.

**Comment by abijames** [comment]
Notes added on JIRA ticket https://slidewiki.atlassian.net/browse/SWIK-1075 re addressing accessibility issues.

**Comment by stavmars** [comment]
@abijames I made some changes based on your cooments re accessibility issues.

**Comment by abijames** [comment]
@kadevgraaf this is ok to merge now.

**Comment by kadevgraaf** [comment]
Works well. Nice functionality!

**Pull request merged**
