### PR TITLE
Swik 1657 userpicture url instead of base64

### PR DESCRIPTION
**Pull request by TBoonX**
I added a new store, service and multiple actions. I stole code from branch SWIK-840-media-file-upload-dialog.

This have to be tested with the SWIK-1687_new_route_for_profilepicture branch of the file-service.

### CODE REVIEW

**Comment by rmeissn** [comment]
Waiting for changes for https://github.com/slidewiki/file-service/pull/6

**Comment by TBoonX** [comment]
The fileservice  have to have jwt authentication on which is not the case

**Comment by TBoonX** [comment]
I activated jwt at the filservces route: SWIK-1657_jwt_is_needed
Atm the image gets transmitted to the service but the npm package image-size throws an error: _TypeError: Uncaught error: unsupported file type: undefined_
I tried Buffer and base64 String but everythings throws this error. Using curl on command line works ...

**Comment by TBoonX** [comment]
I fixed it.
Atm uploading a new image does not update the picture url in the components.

**Comment by TBoonX** [comment]
@dpaun Plese review again.

**Comment by kadevgraaf** [comment]
Cool! 
I also merged https://github.com/slidewiki/file-service/tree/SWIK-1657_jwt_is_needed in file-service via PR https://github.com/slidewiki/file-service/pull/10

**Pull request merged**
