### PR TITLE
Replace SpecialChar plugin for inserting symbols in editor with 'Symbol'

### PR DESCRIPTION
**Pull request by kprist**

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Hi @kprist 
Looks good!
Can you update from master / merge the ckeditor_config.js with the one on master - the config in this PR uses texzilla whilst on master we use Mathjax (and no config.uiColor)

**Comment by kprist** [comment]
Can you check the branch again? I've rebased it to master and re-pushed it, but if you checked it out locally it might still be the older one. If you have it locally, simplest way to review it would be to delete your local copy of the branch and `git checkout` again.

**Comment by kadevgraaf** [comment]
Looks good to me! @abijames can this be merged?

**Comment by abijames** [comment]
I'm struggling to test this. Still can't get ckeditor to show up so I think its my set up. I am happy for it to be merged and then I'll look at it on experimental

**Comment by kprist** [comment]
@abijames, have you run `npm install` since the merge of the ckeditor upgrade to 4.2?

**Pull request merged**
