### PR TITLE
Swik 2494 improve tab focus

### PR DESCRIPTION
**Pull request by aoelen**
Apart from the CSS changes made in the custom semantic UI repository, some HTML changes are needed as wel. This improves the keyboard navigation UX.

### CODE REVIEW

**Comment by abijames** [comment]
@aoelen could you resolve these conflicts which are from the css changes? Then I'll test and merge if ok

**Comment by aoelen** [comment]
@abijames There no conflicts anymore. Most of the changes with respect to the keyboard focus are already on the master branch (since these changes are made in the semantic ui repository). 

This branch can be tested by using keyboard navigation on the deck view page. For example, the tabs in the content modules panel, are now selectable by keyboard.

**Comment by aoelen** [comment]
@abijames There no conflicts anymore. Most of the changes with respect to the keyboard focus are already on the master branch (since these changes are made in the semantic ui repository). 

This branch can be tested by using keyboard navigation on the deck view page. For example, the tabs in the content modules panel, are now selectable by keyboard.

**Comment by aoelen** [comment]
@abijames There are no conflicts anymore. Most of the changes with respect to the keyboard focus are already on the master branch (since these changes are made in the semantic ui repository). 

This branch can be tested by using keyboard navigation on the deck view page. For example, the tabs in the content modules panel are now selectable by keyboard.

**Comment by abijames** [comment]
@aoelen please can you resolve the conflicts on this branch ?

**Comment by kadevgraaf** [comment]
I get a minor warning in my terminal when I run this.
Looks good otherwise 👍 
Can you fix this unique key warning @aoelen ?

```
 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ContentActionsHeader`. See https://fb.me/react-warning-keys for more information.
    in button (created by ContentActionsHeader)
    in ContentActionsHeader (created by storeConnector(ContentActionsHeader))
    in storeConnector(ContentActionsHeader)
    in div
    in div (created by ContentPanel)
    in ContentPanel (created by storeConnector(ContentPanel))
    in storeConnector(ContentPanel) (created by Deck)
    in div (created by Deck)
    in div (created by Deck)
    in div (created by Deck)
    in div (created by Deck)
    in div (created by Deck)
    in Deck (created by storeConnector(Deck))
    in storeConnector(Deck) (created by Application)
    in div (created by Application)
    in Application (created by contextProvider(Application))
    in contextProvider(Application) (created by DragDropContext(contextProvider(Application)))
    in DragDropContext(contextProvider(Application)) (created by storeConnector(DragDropContext(contextProvider(Application))))
    in storeConnector(DragDropContext(contextProvider(Application))) (created by HistoryHandler)
    in HistoryHandler (created by RouteHandler)
    in RouteHandler (created by storeConnector(RouteHandler))
    in storeConnector(RouteHandler) (created by contextProvider(storeConnector(RouteHandler)))
    in contextProvider(storeConnector(RouteHandler))
    in IntlProvider
```

**Comment by aoelen** [comment]
I think the warning about the missing key is caused by changed made in the branch: swik-2299-move-zoom-buttons. A key is missing on line 345 in the file /components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js

**Comment by kadevgraaf** [comment]
Ah good find!
Do you think it is good to fix that together with the new merge conflict in this branch?

**Comment by kadevgraaf** [comment]
Ah good find!
Do you think it is good to fix that together with the new merge conflict in this branch?

**Comment by abijames** [comment]
The conflict needs to be resolved as its related to the keyboard actions that this branch addresses

**Comment by aoelen** [comment]
The conflicts are resolved

**Comment by kadevgraaf** [comment]
Works well. Thanks!

**Pull request merged**
