### PR TITLE
SWIK-525 added configuration of microservices when container starts

### PR DESCRIPTION
**Pull request by bwulff**
SWIK-525

The addresses of the microservices are taken from a set of environment variables and filled into a template, the processed template is written to /nodeApp/configs/microservices.js.
Defaults values for the env variables are defined in the Dockerfile. They can be overwritten via -e argument to the docker command, the environment directive in compose files or an .env file.

### CODE REVIEW

**Comment by bwulff** [comment]
Klaas [1:55 PM]  
hmmm, 
"docker: Error response from daemon: oci runtime error: exec: "./entrypoint.sh": permission denied.”
Even with SUDO

**Comment by bwulff** [comment]
probably entrypoint script has wrong mode...

**Comment by bwulff** [comment]
made entrypoint script executable with commit cbc5073

**Comment by kadevgraaf** [comment]
ERROR in main.js from UglifyJs
Unexpected character '`' [./~/identicons/index.js:38,0]

**Comment by kadevgraaf** [comment]
I'll merge, let see what happens.

**Pull request merged**
