### PR TITLE
Swik 761

### PR DESCRIPTION
**Pull request by Sole-Valero**
In ContentActionsHeader, for each button:
- Removed <a> tag, because it seemed useless
- Added an aria-label attribute
- Title attribute changed to data-tooltip attribute, because the output format seems more consistent with our style
- Added type="button" attribute for html5 consistence

In ContentActionsFooter, for each button:
- Added an aria-label attribute
- Added data-tooltip attribute
- Title attribute changed to data-tooltip attribute in the Expand button, because the output format seems more consistent with our style
- Added type="button" attribute for html5 consistence

In SlideControls:
- added an aria-label attribute
- Title attribute changed to data-tooltip attribute, because the output format seems more consistent with our style
- Added type="button" attribute for html5 consistence

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Looks good!
Perhaps do you also want to make a tooltip for the fork button (above the decktree)?

**Comment by Sole-Valero** [comment]
@kadevgraaf, I have done it at branch SWIK-811

**Comment by kadevgraaf** [comment]
Cool. I can't find it on GitHub (is it published)?

**Comment by Sole-Valero** [comment]
https://github.com/slidewiki/slidewiki-platform/pull/223
Sorry, the name of the branch was wrong in previous post

**Pull request merged**
