### PR TITLE
Swik 1623 my decks review page

### PR DESCRIPTION
**Pull request by TBoonX**
Dejan added two routes: /Sfn87Pfew9Af09aM/user/:username and /Sfn87Pfew9Af09aM
The second one directs to the first one when the user is logged in and provided a secret.
The first one is the My Decks component with three additional buttons: suspend, approve, put back to the queue      plus that clicks on decks opens the links in new tabs

Dejan added actions, one store and one service.
This combines SWIK-1623 and SWIK-1631

### CODE REVIEW

**Comment by kprist** [comment]
The secret in question is set with the server environment variable, `SECRET_REVIEW_KEY`. The relevant user service branch in https://github.com/slidewiki/user-service/pull/30 includes a line in the `docker-compose.yml` file, but it having an empty value won't do, it must be set. The deck service also is up-to-date but its `docker-compose.yml` does not include that variable set. 

I am guessing it's OK to just put any same string in the `docker-compose.yml` files for the platform, user- and deck- services and it may not really be a secret, but it's only for the experimental deployment anyway. Then it's up to deployment ( @bwulff and @paulbaptista ) to actually set a real secret in stable and slidewiki.org.

**Comment by kadevgraaf** [comment]
How to test this?
On localhost, when I visit, http://localhost:3000/Sfn87Pfew9Af09aM/user/kadevgraaf
I get prompted for the secret, for which '' (empty) works,
I then get the message in the screenshot below; 
screen shot 2017-09-25 at 20 18 01
which seems fine, but makes this seem untestable (I do not see an adapted my decks page with stuff to review)
In my browser console I do get the following error:
`GET http://localhost:3000/api/userreview.nextreviewable;jwt=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcyLCJ1c2VybmFtZSI6ImthZGVncmFhZiIsImlhdCI6MTUwNjM1NzkxOH0.iyQpE1exFDapED_o92Q_6FNCklI4p8f6hVpcAhE5g5kNzVSushydY91Zu_L_b6YM9OKmTDeSkZPJDDSTVYn4Uw;secret=?returnMeta=true 404 (Not Found)
_createXHR @ index.js:222
createXHR @ index.js:50
io @ http.client.js:171
doXhr @ http.client.js:167
get @ http.client.js:241
executeRequest @ fetcher.client.js:245
Request.end @ fetcher.client.js:168
read @ fetcher.client.js:392
getNextReviewableUser @ getNextReviewableUser.js:8
(anonymous) @ callAction.js:21
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
(anonymous) @ callAction.js:19
callAction @ callAction.js:18
executeActionProxy @ FluxibleContext.js:150
executeAction @ FluxibleContext.js:163
componentExecuteAction @ FluxibleContext.js:267
(anonymous) @ UserProfileReview.js:28
Promise resolved (async)
componentDidUpdate @ UserProfileReview.js:27
(anonymous) @ makeAssimilatePrototype.js:15
measureLifeCyclePerf @ ReactCompositeComponent.js:75
(anonymous) @ ReactCompositeComponent.js:728
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
ReactComponent.setState @ ReactBaseClasses.js:64
onStoreChange @ connectToStores.js:53
(anonymous) @ makeAssimilatePrototype.js:15
emit @ index.js:150
emitChange @ BaseStore.js:73
fillInUser @ UserProfileStore.js:183
callHandler @ Action.js:67
handlersEach @ Action.js:45
execute @ Action.js:44
dispatch @ DispatcherContext.js:111
(anonymous) @ fetchUser.js:59
run @ setImmediate.js:49
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
requestSucceeded @ fetcher.client.js:170
getDone @ fetcher.client.js:250
success @ http.client.js:150
(anonymous) @ http.client.js:218
cbOnce @ index.js:62
loadFunc @ index.js:129
XMLHttpRequest.send (async)
_createXHR @ index.js:222
createXHR @ index.js:50
io @ http.client.js:171
doXhr @ http.client.js:167
get @ http.client.js:241
executeRequest @ fetcher.client.js:245
Request.end @ fetcher.client.js:168
read @ fetcher.client.js:392
fetchUser @ fetchUser.js:24
(anonymous) @ callAction.js:21
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
(anonymous) @ callAction.js:19
callAction @ callAction.js:18
executeActionProxy @ FluxibleContext.js:150
executeAction @ FluxibleContext.js:163
componentExecuteAction @ FluxibleContext.js:267
componentDidUpdate @ HeaderDropdown.js:23
(anonymous) @ makeAssimilatePrototype.js:15
measureLifeCyclePerf @ ReactCompositeComponent.js:75
(anonymous) @ ReactCompositeComponent.js:728
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:209
perform @ Transaction.js:156
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
ReactComponent.setState @ ReactBaseClasses.js:64
onStoreChange @ connectToStores.js:53
(anonymous) @ makeAssimilatePrototype.js:15
emit @ index.js:129
emitChange @ BaseStore.js:73
loadNewNotificationsCount @ UserNotificationsStore.js:45
callHandler @ Action.js:67
handlersEach @ Action.js:45
execute @ Action.js:44
dispatch @ DispatcherContext.js:111
(anonymous) @ loadNewUserNotificationsCount.js:13
run @ setImmediate.js:49
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
requestSucceeded @ fetcher.client.js:170
getDone @ fetcher.client.js:250
success @ http.client.js:150
(anonymous) @ http.client.js:218
cbOnce @ index.js:62
loadFunc @ index.js:129
XMLHttpRequest.send (async)
_createXHR @ index.js:222
createXHR @ index.js:50
io @ http.client.js:171
doXhr @ http.client.js:167
get @ http.client.js:241
executeRequest @ fetcher.client.js:245
Request.end @ fetcher.client.js:168
read @ fetcher.client.js:392
loadNewUserNotificationsCount @ loadNewUserNotificationsCount.js:7
(anonymous) @ callAction.js:21
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
(anonymous) @ callAction.js:19
callAction @ callAction.js:18
executeActionProxy @ FluxibleContext.js:150
executeAction @ FluxibleContext.js:163
componentExecuteAction @ FluxibleContext.js:267
componentDidMount @ HeaderDropdown.js:17
(anonymous) @ makeAssimilatePrototype.js:15
(anonymous) @ ReactCompositeComponent.js:264
measureLifeCyclePerf @ ReactCompositeComponent.js:75
(anonymous) @ ReactCompositeComponent.js:263
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:143
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:319
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ client.js:425
(anonymous) @ promiseCallback.js:21
Promise resolved (async)
promiseCallback @ promiseCallback.js:20
rehydrate @ Fluxible.js:215
renderApp @ client.js:415
Promise resolved (async)
(anonymous) @ client.js:449
(anonymous) @ main.js:113186
(anonymous) @ main.js:113187
__webpack_require__ @ bootstrap a19fe9f5bdecf343daa1:688
fn @ bootstrap a19fe9f5bdecf343daa1:109
(anonymous) @ main.js:241621
__webpack_require__ @ bootstrap a19fe9f5bdecf343daa1:688
(anonymous) @ bootstrap a19fe9f5bdecf343daa1:789
(anonymous) @ bootstrap a19fe9f5bdecf343daa1:789
kadevgraaf:1 Uncaught (in promise) timer`

**Comment by dpaun** [comment]
We should probably create some new users to fill the queue...
@TBoonX , could you tell us whether new users, upon registering, are added to the queue or they need to create some decks first?
btw, a call with empty string for the secret fails in my case, since, I believe, it's not allowed in the routes of the user-service.

**Comment by TBoonX** [comment]
@dpaun Correct the secret could not be empty.
Users have to have the following attributes in order to be added to the queue:
authorized !== false
deactivated !== false
reviewed !== false
registered > 2017-07-19
number of owned decks>1

They are added via manually call of application/queue/update.js or daily via crontab.

@kadevgraaf In order to test it correctly you need this platform branch, the user-service branch SWIK-1610_foundation and the deck-service master branch with the local mongodb. With this you need to add users via sign up to the database. Or you import an dump (if its older than 2017-07-19 you need to change line 1052 of handler.js in user-service before starting it) and than execute application/queue/update.js

**Comment by kprist** [comment]
Merging was performed after reviewing that it doesn't break anything, which it doesn't. Further review as to the actual functionality this provides is pending.

**Pull request merged**
