### PR TITLE
Mobile view improvements

### PR DESCRIPTION
**Pull request by rmeissn**
* Hide DeckTree and show Breadcrumb in Slide-/Deckview on mobile (not on Tablet)
* Deactivated Edit Mode + Hide buttons on top of the slide/deck (New Slide, Delete, ....) (mobile)
* Stack 3 thumbnails in DeckView mode (mobile)
* Hide user information on My Decks page (mobile)
* Compressed footer for mobile devices
* Increased header sidebar button size + removed home button + added logo (mobile)
* Added message to deck-/slideview that mobile editing is not possible (mobile, tablet)
* Improved settings spacing (tablet) and settings menu width (mobile)
* Improved spacing of "My Groups" on mobile devices
* Stretched Mail+Password input fields for SignIn Form (mobile)
* Improved mobile, tablet and computer view of SignUp, SignIn, ResetPassword
* Hide optional search options by default (mobile)
* Hide filter options for notifications by default (mobile)
* Reordered private and public user information (mobile)
* Stacked the "My Decks" Cards (mobile)
* Hide deck collection creation (mobile)
* Hide slide progress numbers in content action footer (slide/deck view) on mobile
* Move content action items to dotted menu in content action footer  (slide/deck view) on mobile

Will continue to push improvements to this PR

### CODE REVIEW

**Comment by abijames** [comment]
on testing on a tablet , found that the slide editor buttons Add text box, image etc that launch do not work with a touch screen (ipad or windows). This currently works on both OS with experimental so this seems to be a problem with the build

**Comment by Sole-Valero** [comment]
Checked with my Samsung SM-G350F
- In My Decks view, deck Titles overflows the deck card if the words are large. Perhaps it should better to see only one deck by row (I see two)
- When you select an slide, the message to advice users about they can't edit on a mobile is shown in a completely different colour from ones we usually uses
I didn't add a deck, because I haven't got one in my mobile.

**Comment by rmeissn** [comment]
@abijames: Me and @kadevgraaf think this is related to @Sole-Valero deployment, as the error message states something about cross domain errors, related to the import service beeing hosted at experimental (but platform running on Soles domain). We can't reproduce these errors at our local devices.

@Sole-Valero I've changed the My Decks view to show only one card per line on mobile devices.
Which color do you recommend instead?

**Comment by Sole-Valero** [comment]
Error color used in other components: #FFF6F6
image

**Comment by rmeissn** [comment]
@Sole-Valero But it is not really an error. It's just a information (but a pretty important one). I'm fine to change this to slight blue or slight yellow (used for information messages).

**Comment by Sole-Valero** [comment]
@rmeissn good point. @abijames, @rmeissn Do you remember any other place in our platform in which we give some info without a sweet alert? In order to select the same one.

**Comment by rmeissn** [comment]
The only place I remember having something similar is: https://platform.experimental.slidewiki.org/user/rmeissn/settings/integrations

**Comment by rmeissn** [comment]
Ticket to this PR: https://slidewiki.atlassian.net/browse/SWIK-2102

**Comment by Sole-Valero** [comment]
This light blue is also used in our platform for remarking: #F8FFFF

**Comment by abijames** [comment]
@rmeissn please can you resolve the conflicts and update this branch with master so that we can test before merging thanks!

**Comment by rmeissn** [comment]
@abijames Done

**Comment by abijames** [comment]
@rmeissn thank you for updating the branch. On testing it, I feel we need to improve some more areas before it goes into the a release. Particularly, how you move through slides from the deckview (or without a decktree) and also I had some issues with our latest attempts to support zoom in slides (@kadevgraaf slide remains large on a mobile device). 
But could you also change the message "You are on a mobile device. If you want to modify slides, please change to a desktop computer." too.... "You are viewing the mobile version of SlideWiki. If you wish to edit slides you will need to use the desktop version."

**Comment by rmeissn** [comment]
I've changed the text according to your proposal. Do you think users will know to use a tablet/laptop/desktop computer, if you tell them "...use the desktop version"? I guess my parents won't know how to reach the "desktop version".
Would you be so kind to post a list of areas we need to work on?

**Comment by rmeissn** [comment]
@abijames What's the status of this PR? I had to modify much files to improve mobile views. Thus merge conflicts will appear often, as other people are changing these files as of their work too.
In my opinion, it's better to have some mobile improvements now instead of waiting for them to become perfect quality. We can always improve things later.

**Comment by abijames** [comment]
@rmeissn as per my comment, we need a means of moving through slides from the deck view as without the decktree the only way to get into the deck is by clicking on one of the thumbnails (not so intuitive).

I will test again and then list remaining tasks

**Comment by abijames** [comment]
@rmeissn please could you update this branch with master? Then if all ok I suggest we merge and create further tasks to improve

**Comment by rmeissn** [comment]
I resolved the merge conflicts. But I am absolutely not sure if I resolved them correctly. Please make sure that the changes from the commit 3484df4 doesn't break anything. Files that have been edited in this commit:
components/Deck/ContentPanel/ContentActions/ContentActionsHeader.js
components/Deck/ContentPanel/DeckModes/DeckViewPanel/DeckViewPanel.js
components/Deck/ContentPanel/SlideModes/SlideControl.js
components/Deck/Deck.js
components/Login/LoginModal.js
components/User/UserRegistration/UserRegistration.js

**Comment by abijames** [comment]
@rmeissn I am ok for this to be merged for the conflicts are resolved 

I have made a ticket for an improvement to the deckview for improvements to help with navigating into the deck https://slidewiki.atlassian.net/browse/SWIK-2220

**Comment by rmeissn** [comment]
I've resolved merge errors (hope that's how it is intended to look?!).
Will merge this now.

**Comment by kprist** [comment]
Checked the merge as far as code I've written, it was done correctly, not expecting errors there :) :+1:

**Pull request merged**
