### PR TITLE
Swik 1320 deck groups

### PR DESCRIPTION
**Pull request by schatzopoulos**
This PR introduces deck collections (deck groups) in the platform: 
- a deck collection can be created and assigned to a deck in the deck edit panel
- the creator of the deck collection can assign a user group to the collection, meaning that the members of the user group can add/remove/reorder decks in this collection 
- in the "my decks" page (probably can be renamed to "my profile") a menu was added below user information with the option to navigate to "my deck collections"
- in "my deck collections page" a user can edit or delete deck collections that he created
- each deck collection has a page that shows the decks included
- decks in a collection can also be reordered

in order to test just this platform branch the following PR in deck-service should be merged first:
https://github.com/slidewiki/deck-service/pull/123

!!! Please DO NOT merge this now, just suggest improvements/fixes that can make this feature more usable

### CODE REVIEW

**Comment by abijames** [comment]
I am putting comments on the JIRA ticket https://slidewiki.atlassian.net/browse/SWIK-1320 as there a number of different interfaces that I am commenting on.

**Comment by schatzopoulos** [comment]
I've addressed the issues about accessibility that you reported on the JIRA ticket.
Please can you check this branch again @abijames ?

**Comment by kadevgraaf** [comment]
Hi Serafeim. Thank for the improvements! Do you want to resolve merge conflicts? I want to merge this PR, but you know best how to resolve merge conflicts I think.

**Comment by schatzopoulos** [comment]
Hi @kadevgraaf ! I've resolved the conflicts but I am not sure if Abi has checked this PR after the last improvements. @abijames are you ok for this to be merged?

**Comment by abijames** [comment]
I will check it the latest version later today

**Comment by abijames** [comment]
@schatzopoulos @kadevgraaf  I have had a look at the PR again. I think it would be good to merge it now and ask people for feedback over the next few days as I think there could be a few more tasks to integrate this functionality into the UI (e.g. adding a deck to collection from the the collection, adding My Deck collections to the settings page). So getting feedback and then completing these additional tasks during this sprint would be the goal!

**Pull request merged**
