### PR TITLE
Swik 2383 support education levels

### PR DESCRIPTION
**Pull request by kprist**

### CODE REVIEW

**Comment by kprist** [comment]
Deck service PR already merged: https://github.com/slidewiki/deck-service/pull/146

**Comment by abijames** [comment]
I've push small corrections to the accessibility to the page. Note at the moment the Education level dropdown has an empty option and is set to be a required field in the code but this is not showing in the UI (probably semantic-ui-react bug) and also the form validation does not report that leaving this field empty is invalid. If this is ok for the service, I am ok for this to be merged.

**Comment by kprist** [comment]
The field is NOT required by purpose. Are you OK with this? Is it otherwise OK ?

**Comment by abijames** [comment]
required attribute removed on education level

**Pull request merged**
