### PR TITLE
Swik 686 autocomplete

### PR DESCRIPTION
**Pull request by schatzopoulos**
autocomplete in header search box

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Works well. The revision search is I think very valuable. Nice improvement!

One minor optimization is the hyperlinks that sometimes point to /slideview, e.g.
www.domain.org/slideview/625-1
and other times to /deck/slide, e.g., 
www.domain.org/deck/51-1/slide/378-1

Was this intended/designed? Personally I prefer the latter hyperlink that points to e.g,
www.domain.org/deck/51-1/slide/378-1 because you can directly start editing and see the deck in which the slide is located.

Sorry for not discovering this earlier. Anyways it is a minor optimization which we can do anytime.

**Comment by abijames** [comment]
This pull request has removed the Form field label added to the search box in PR 205 https://github.com/slidewiki/slidewiki-platform/pull/205.

Please can we fix this?

**Comment by schatzopoulos** [comment]
@abijames Yes! I am fixing this.

**Comment by schatzopoulos** [comment]
@kadevgraaf Hyperlinks that point to /slideview is an issue related to https://slidewiki.atlassian.net/browse/SWIK-707 . Slide revisions that are inactive don't have an associated deck so a link of the type /deck/slide can't be created.
We should first decide if we want to show inactive slide revisions in the search results and if yes, then how we can create a link for these revisions. (2 possible solutions are stated in the comments in the JIRA ticket above)

**Comment by kadevgraaf** [comment]
Ah yes. Good discussion. Thanks for the link and 2 proposals!

**Pull request merged**
