### PR TITLE
Swik 1182 creation pagination for question panel

### PR DESCRIPTION
**Pull request by andyfaizan**
The UI is commented since the use of pagination is still being discussed.

To enable pagination,
In file "actions/loadContentQuestions.js", line 7, change maxQuestions to a smaller number e.g. 5
In file "components/Deck/ContentModulesPanel/ContentQuestionsPanel/ContentQuestionsPanel.js", un-comment line 184

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Hi Andy!

I tried to enable pagination: 

> In file "actions/loadContentQuestions.js", line 7, change maxQuestions to a smaller number e.g. 5
> In file "components/Deck/ContentModulesPanel/ContentQuestionsPanel/ContentQuestionsPanel.js", un-comment line 184

But I get the following error:
screen shot 2017-06-07 at 14 44 03

**Comment by andyfaizan** [comment]
Hey Klaas! Was I suppsoed to locally merge and then make a pull request? I pulled changes from master on my local 1182 branch and it seems to work fine.

**Comment by andyfaizan** [comment]
I pulled the merged changes and tried it out. Worked fine on my side. o.O

**Comment by kadevgraaf** [comment]
My uncommenting went wrong. Sorry :) 
Works fine! I am good with merging this if you are @abijames

**Comment by bwulff** [comment]
Should we wait with this merge until we know that the back-end is also ready?

**Comment by kadevgraaf** [comment]
I think it is fine to merge. The mockup data will have to be replaced with back-end data anyways, regardless of pagination.

**Pull request merged**
