### PR TITLE
Swik 1171 more user information when searching

### PR DESCRIPTION
**Pull request by TBoonX**
Basically I make usage of the change of the _search user_ route in the user service which now returns also the organization and country. These two information are displayed in group edit, deck edit and group details. I improved the UI there also.
This have to be merged wih the repos in userservice and deckservice (same name)

### CODE REVIEW

**Comment by TBoonX** [comment]
@abijames the branch of the user-service and deck-services was merged into master. You could test this PR while using all the experimental.slidewiki.org URLs in the platform.

**Comment by kadevgraaf** [comment]
Works well!
@abijames  - once OK with you I will merge this.

**Comment by abijames** [comment]
Happy for this to be merged but 2 minor suggestions for improving it....
- Could you put the country in ( ) to make it clearer what this is e.g. username, organisation (Country)
- It is not possible to see a list of users without typing in a character. Is this a setting in the dropdown settings from Semantic UI as there examples allow you to see a list of a all the options by opening the dropdown. I think this could be important if people are unsure of usernames.

**Comment by TBoonX** [comment]
@abijames :
1.: Good idea!
2.: OK how many and which usernames should be displayed then? I could try activating this but I am not sure if the service is able to handle this. Let me check.

**Comment by abijames** [comment]
@TBoonX have a look at https://semantic-ui.com/modules/dropdown.html#search-selection - this lets you see the list without typing in anything into the search box

**Comment by TBoonX** [comment]
@abijames I know the examples. But I am using a remote content dropdown which gets the data from the service. When usernames should be shown without any input, I  need to know which usernames I should show. The first ten (bad names)? ten dummy usernames (I dont know if this works with semantic-ui)? Or what is your idea?

**Comment by abijames** [comment]
@TBoonX first 8 names would be good.

**Comment by TBoonX** [comment]
@abijames : I realized your request, but its on the service side - @kadevgraaf  have to merge https://github.com/slidewiki/user-service/pull/23

**Comment by kadevgraaf** [comment]
Done :)

**Comment by kadevgraaf** [comment]
Works well! 👍

**Pull request merged**
