### PR TITLE
SWIK 2273   Toolbar sometimes covers save button in edit mode

### PR DESCRIPTION
**Pull request by kadevgraaf**

### CODE REVIEW

**Comment by kadevgraaf** [comment]
merge for testing by @abijames

**Comment by abijames** [comment]
@kadevgraaf did you mean to merge this? I am still testing as I can't get keyboard access to work and I think the buttons are too small.

**Comment by aoelen** [comment]
@abijames I increased the button size and improved the keyboard accessibility. 

To enable keyboard navigation in CKEditor, click on an editable text area (so the editor will appear), then press Alt+F10 on your keyboard. Navigate between the items using tab and left/right arrow keys.

**Comment by aoelen** [comment]
@abijames I increased the button size and improved the keyboard accessibility. 

To enable keyboard navigation in CKEditor, click on an editable text area (so the editor will appear), then press Alt+F10 on your keyboard. Navigate between the items using tab and left/right arrow keys.

**Pull request merged**
