### PR TITLE
Swik-630 special characters of pptx files

### PR DESCRIPTION
**Pull request by TBoonX**
I encoded the filename for HTTP

### CODE REVIEW

**Comment by TBoonX** [comment]
Please do not merge it!!!!!!!!

**Comment by kadevgraaf** [comment]
I wont :)

Op donderdag 29 september 2016 heeft Kurt Junghanns <
notifications@github.com> het volgende geschreven:
> Please do not merge it!!!!!!!!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/7P2-C0QJWVFnXrcbrnN_BOmCxTPPDNmZbiJdCL_G3IxWPBfNDwOq5JvCXkla7_4ddzWRrKF9r2vEJBfY3wVlb-Di-HDna4cRZQK7bCB4zmgVrQ91HN4y3todc5xWPneBtDOKWnMbQj4omygNAVeiFm5v7CVSIw=s0-d-e1-ft#https://github.com/notifications/beacon/AP9QkObdIzxXZD89dddHoLF4homHb3odks5qu3FegaJpZM4KI5DM.gif>

**Comment by kadevgraaf** [comment]
Hi @TBoonX, what is the status of this PR, or perhaps do you want to combine this with work on SWIK-748? 
From https://slidewiki.atlassian.net/browse/SWIK-748 import of filenames with special characters seems to work* on experimental currently. (*except for setting author)

**Comment by TBoonX** [comment]
Roy and me thought my current solution (escaping everything with whitespaces and encoding it for HTTP) looks extremely bad in the frontend (the filenames are not really possible to read). Thus we decided to keep this bug.
It doesn't work! When I import the named file then the deck is emtpy.
Thus I dont know how to fix this. Only showing the hint "Please remove special characters (ü é /o ae, etc..) from the name of your powerpoint file" as you proposed seems a good tradeoff for now.

**Pull request closed without merging**
