### PR TITLE
Swik 1449 refine tag panel

### PR DESCRIPTION
**Pull request by schatzopoulos**
- Adds autocomplete functionality when inserting tags
- Tag Panel from slides needs to be removed

### CODE REVIEW

**Comment by abijames** [comment]
I am generally happy with the UI but there needs to be some accessibility fixes.

At the moment, if you click on a tab the deckfamily page opens but does not include the current deck. @kprist is this the issue you were commenting?

**Comment by schatzopoulos** [comment]
@abijames this definitely shouldn't happen. Probably this is an issue with the synchronization of the search index on testing. I have to check it with Ben but I remember fixing it during the hackathon. Maybe something has changed in the deployment.

**Comment by schatzopoulos** [comment]
@abijames I added some aria-labels in tags and button in the tags panel. Please, inform me if further accessibility issues need to be resolved.

The issue about deckfamily seems to be working now, so it was probably something in the server deployment that has been fixed.

**Comment by abijames** [comment]
ok to merge. Some accessibility issues still to deal with but functionality is a good improvement @kadevgraaf

**Pull request merged**
