### PR TITLE
Swik 2504 download questions

### PR DESCRIPTION
**Pull request by nk1g09**
Download button in question content panel for selection modal & download of questions

### CODE REVIEW

**Comment by abijames** [comment]
Tested, works well. This will need to have accessibility improved later.
@kadevgraaf can you merge?

**Comment by kprist** [comment]
Download does not happen without any error or warning. @nk1g09 can you check this again?

**Comment by nk1g09** [comment]
> Download does not happen without any error or warning. @nk1g09 can you check this again?

What browser is this in? I just checked it again and it works for me in chrome and edge.

**Comment by kprist** [comment]
Firefox; I'll check again in Chrome and let you know, thanks!@

**Comment by nk1g09** [comment]
> Firefox; I'll check again in Chrome and let you know, thanks!@

Ah yes, there was a bug in Firefox. Have pushed a change which should now work in firefox, edge and chrome.

**Pull request merged**
