### PR TITLE
Swik-675 remaking user profile page

### PR DESCRIPTION
**Pull request by TBoonX**
Deleted tabs in my profile view
used thumbnail component in DeckCard

### CODE REVIEW

**Comment by ali1k** [comment]
I still see a redundant '}' after the name of my deck! Could you remove that character?
Can you also check the 'Delete my account' functionality! if it is not implemented yet, can you hide it from the profile?

**Comment by TBoonX** [comment]
I fixed these two bugs.
If a user visits the profile settings page an error is thrown - I will investigate this now

**Comment by ali1k** [comment]
sounds good! let me know when it is ready!

**Comment by TBoonX** [comment]
Its not an error. the console logs a 404 when a user have no decks, which is correct.
Ready to merge! - pulled master again

**Comment by ali1k** [comment]
good! let's merge it then!

**Pull request merged**
