### PR TITLE
Swik 930 slide revision switch by anonymous user

### PR DESCRIPTION
**Pull request by stavmars**
This PR hides the revert button for not logged in users.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Works well on localhost 👍

**Comment by abijames** [comment]
@stavmars functionally this works. But there is nothing in the UI to show the user which revision they are viewing. Can you implement something like the unhide icon next to the revision that is currently being displayed.

Also, when signed in (but not the owner) I can change the active revision.

**Comment by abijames** [comment]
@stavmars @kadevgraaf shall we merge this anyway and make new tasks for the additional functionality?

**Comment by kadevgraaf** [comment]
Sounds good. This is already a nice improvement.

**Comment by stavmars** [comment]
@abijames  yes, I think that would be best.

**Pull request merged**
