### PR TITLE
Swik 824 Add and Edit deck/slide activities

### PR DESCRIPTION
**Pull request by dpaun**
Creating activities when adding or editing a deck/slide (related to activity feed panel, notifications).
Also moved creation of comment activities from discussion service to the platform.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Hi Dejan. The new features look good! 
Do you want to resolve the conflicts -> the user group deck edit and forking PR introduced a lot of changes.

**Comment by dpaun** [comment]
Yes, of course.

**Comment by kadevgraaf** [comment]
works well!
One minor thing - when I edit a slide, it shows the html title of the slide in the activities section when viewing the deck (deckview) that contains the slide.
screen shot 2017-03-30 at 16 41 57

**Comment by dpaun** [comment]
Hmm... Yes.
Currently, when a deck is selected, the activity feed panel displays also all activities of subdecks and slides of the selected deck.
I can easily change this if it's not what we want.

**Comment by kadevgraaf** [comment]
I think that is a nice feature! 
It's only that the slide title is between <p> tags, but if that takes a lot of work to change we can merge this and fix the title next sprint.

**Pull request merged**
