### PR TITLE
SWIK-1194 Improve Cropper Accessibility issues (parts)

### PR DESCRIPTION
**Pull request by rmeissn**
The initial cropper window for uploading user pictures is now always sized to it's maximum. This was a complain of @abijames as of SWIK-1194.
This PR interferes with #597 --> My student assistant is searching for an solution.

### CODE REVIEW

**Comment by abijames** [comment]
I have approved this but suggested changes to the hidden description for the modal window to help screen reader users. Then can be merged.

**Comment by rmeissn** [comment]
Added the suggestions of @abijames .
This branch is still not meant to be merged, as it interferes with PR #597 . The new version of the library won't allow use the "maxwidth" option for the crop command.

**Comment by abijames** [comment]
@rmeissn @kadevgraaf just noticed this PR is still open. Is there an update on when it can be merged?

**Comment by rmeissn** [comment]
@abijames I'll ask my student about his progress.

**Comment by kadevgraaf** [comment]
@rmeissn  - Yes lets create our own fork 👍

**Comment by rmeissn** [comment]
@tinsaye already forked the repo to https://github.com/slidewiki/react-image-cropper
He will merge needed changes in the next couple of days and I will publish it to NPMjs ASAP

**Comment by kadevgraaf** [comment]
Cool, thanks!

**Comment by rmeissn** [comment]
My student assistant committed all needed changes to our own repo and I published a new lib to npmjs - (slidewiki-react-image-cropper)[https://www.npmjs.com/package/slidewiki-react-image-cropper].
This branch does not conflict with #597 anymore and should be finally fine to merge.
@abijames Can you please recheck for accessibility and style?

**Comment by abijames** [comment]
@rmeissn on testing the branch I occasionally got this error message. It needs to be more understandable.
image

re the cropper, do you expect to be able to move this with the keyboard as I wasn't able to do that? However, it is acceptable as it is.

**Comment by kadevgraaf** [comment]
The error message is super-effective... for part of the users :)

**Comment by rmeissn** [comment]
@abijames @kadevgraaf is the message too silly? What do you propose instead? At least the last part of the message states the problem and a possible solution ^^
@abijames Have you tried some exotic picture format? The cropper should work for at least png and jpeg and all sizes (except pictures that are way too small, like 50x50px).
About keyboard accessibility: This has been no requested feature until now. See SWIK-1194. Do you mind opening a new feature request ticket and indicating its priority?

**Comment by abijames** [comment]
@rmeissn photo attached. Sometimes it worked, sometimes it didn't...
abi-squ

I would suggest a simple message like "Sorry, we could not upload your photo at this time. Please try again."

If there are min or max size requirements then we could add them to the message. But it is best to keep as simple as possible as it will have to be translated.

Re additional feature request, I will do that as a feedback ticket once it is merged.

**Comment by rmeissn** [comment]
I've exchanged the texts to: titel: "Photo selection not processible!", content: "Sorry, we could not process your chosen selection. Please try again with a different photo or selection."

Hmmm, seems to be an error with the cropper library. Will open up a bug report in our Jira.

Apart of this bug: Ready to merge?

**Comment by rmeissn** [comment]
Any updates to this PR?

**Comment by abijames** [comment]
@rmeissn Ben and Klaas wanted to hold off merging this into the current release as there were lots of code changes. As I recall once that release is out then they will look at it

**Comment by kadevgraaf** [comment]
I forked this branch to https://github.com/slidewiki/slidewiki-platform/pull/757/files  from an earlier stage before having some bad merges with master

**Pull request closed without merging**
