### PR TITLE
Swik 2012 fix edit question button visibiilty

### PR DESCRIPTION
**Pull request by dpaun**
This is a very small fix for the question edit button visibility (permission).

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Thanks @dpaun  !
Already works nice for correctly showing the edit-button.
Currently when I edit a question I just added and press "save" nothing happens. Are you able to reproduce this?

**Comment by dpaun** [comment]
Yes, I'm able to reproduce it. Thanks! It's a bug, I'll fix it soon.

**Comment by dpaun** [comment]
The problem with editing a question should be fixed now.

**Comment by kadevgraaf** [comment]
Works like a charm. Thanks!

**Pull request merged**
