### PR TITLE
Accessible forms

### LINKED ISSUE #1186: Fix bugs and inconsistencies with dropdowns
Currently in SlideWiki different types of dropdowns (or select) components are used. E.g. Semantic UI JQuery, Semantic UI React, native browser select and custom made dropdown elements. This results in inconsistent behavior of those components. Additionally, it is hard to maintain these different components (i.e. making them accessible etc.).

I'm trying to replace all dropdowns by the Semantic UI React component. This component automatically adds (most) aria-* attributes. I replace this at several pages now, but I need someone to test the accessibility thoroughly before I continue to replace this everywhere. In case some of these dropdowns are not accessible, I will fork Semantic UI React, and implement this myself (afterwards merge it back into Semantic UI React).

I started this work in the branch: `Consistent-dropdowns`. The following dropdowns have been replaced:

- Personal settings: User Interface Language (regular dropdown)
- Personal settings: Country (searchable dropdown)
- Deck settings: Choose deck theme (regular dropdown)
- Deck settings: Education Level (regular dropdown)
- Deck settings: Add users for edit rights (async searchable dropdown without selection)

@VivienDZB Do you have a local version of SlideWiki running? If so, can you check out the branch locally and test if the replaced dropdowns are fully compliant to the accessibility standards? Thanks!

### LINKED ISSUE #1202: Consolidate errors messages on from fields

### LINKED ISSUE #1242: Error identification (WCAG 3.3.1)
**Request:** The intent of this Success Criterion is to ensure that users are aware that an error has occurred and can determine what is wrong. The error message should be as specific as possible. In the case of an unsuccessful form submission, re-displaying the form and indicating the fields in error is insufficient for some users to perceive that an error has occurred. Screen reader users, for example, will not know there was an error until they encounter one of the indicators. If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text.

**Issues:** 

1. https://slidewiki.org/ 
- In the "Login" dialog, the error message is displayed (if the e-mail address or password is not entered correctly) below the form fields. --> **This also effects other pages!**
--> The error message should be at the top of the page. In addition, the relevant form field is clearly highlighted. Alternatively, error messages that are positioned close to the form field, but are not part of the label, can be linked with `aria-labeledby` or `aria-describedby`.

2. https://slidewiki.org/contactus
- If none of the required form fields are filled in, an error message only appears in the field "Email". This is a pop-up that does not remain on the relevant field when scrolling.
- If you leave out the "Type of report" field (all other necessary fields are otherwise filled out), no error message appears. The contact form cannot be sent.
--> The error messages should be designed consistently within and across pages. The implementation on the page "Add Deck" could serve as a model.

### LINKED ISSUE #1243: Labels or Instructions of form fields (WCAG 3.3.2)
**Request:** The intent of this criterion is to have content authors place instructions or labels that identify the controls in a form so that users know what input data is expected.

**Issues:** 
1. https://slidewiki.org/
- The form fields in the registration dialog are not adequately labeled. (**This also effects other pages!**)

2. https://slidewiki.org/search?keywords=accessibility&sort=score 
- The form field "Type your search terms here" only has a placeholder text. This is not sufficient, it is not reliably reproduced by screen readers.

3. https://slidewiki.org/deck/127411/_/slide/836159-2/836159-2:1/edit ; https://slidewiki.org/deck/127411/_/slide/836159-2/836159-2:1/markdownEdit

- The text fields on the page for editing the slides are input fields that do not contain an `aria-label` element.

4. https://slidewiki.org/search?keywords=accessibility&sort=score
- The input field for the search, as well as some fields within the "Advanced options" do not have a `label` element.

**Solution:**
Form fields should be labeled using the elements `label` or `legend`.

### PR DESCRIPTION
**Pull request by aoelen**
Fixes #1242, fixes #1202, fixes #1243, fixes #1186

Using the Semantic UI implementation to make form errors (and forms in general) more accessible. Now only replaced text, password and checkbox inputs. Still requires some work for select elements. 

To make form fields more accessible: 
- Labels are linked to the respective inputs
- Field errors are shown next to the field and general form errors are displayed on top
- Errors are linked to inputs by using `aria-describedby` (in case of a field error)
- Errors are pronounced by screen readers by using `role="alert"`

To do:
- [ ]  Automatically focus on the first input with an error (needs a Semantic UI change because the ref is not passed when using `Form.Field`)
- [x] Check other inputs as well (select etc.) 

Field error: 

General form error:

@VivienDZB currently it is not merge to master yet, so you cannot test it yourself. But do you think this is sufficient to fix the problems described in issue #1242? 

Forms to check
- [x]  Login
- [ ]  Registration
- [x]  Add deck
- [x]  Alter my personal data
- [x]  Change password
- [x] Deck tags
- [x]  Deck settings
- [ ]  Add source
- [ ]  Add comment
- [ ]  Create a new playlist
- [x]  Contact
- [x] Deck language selector

### CODE REVIEW

**Comment by VivienDZB** [comment]
@aoelen Yes, I guess, this should fix the problems in #1242 . It might also effect/solve the issues described in #1243.

**Comment by aoelen** [comment]
Great, then I'll continue implementing this in the other forms as well

**Comment by aoelen** [comment]
In the end, I had to fork Semantic UI because there were too many changes. Especially changing the default behaviour to open a dropdown on focus. Hopefully we can merge these changes later to Semantic UI React. 

Most of the issues are now fixed related to forms

**Comment by aoelen** [comment]
I asked @rezatavakoli to review this. Afterwards, we will merge it to master, so you can also test it @VivienDZB

**Pull request merged**
