### PR TITLE
Swik 1958 student performance prediction prototype

### PR DESCRIPTION
**Pull request by dpaun**
This is a prototype for the student performance prediction module. The functionality can be checked on the user settings page.
Related: deliverable D3.1 SlideWiki learning analytics

### CODE REVIEW

**Comment by abijames** [comment]
I have tried to run the branch locally but I can't see this feature. As it is marked beta I am less concerned about the UI for now as we can make small changes after the release.

**Comment by abijames** [comment]
Please do not merge into end-October release. It has been agreed this needs further work so will be a late addition / experimental feature, particularly as we need data in the system to get it to work effectively.

**Comment by dpaun** [comment]
@kprist , @kadevgraaf , @abijames , 
Since the reviewers might read about this functionality in the deliverable D3.1 and not be able to find it on the platform, I was wondering should we merge this soon (to experimental only, of course)?
As Kostis said earlier, this feature is quite disconnected from the rest of the platform UI, so we don't expect any issues with breaking things elsewhere.

**Comment by abijames** [comment]
@kprist , @kadevgraaf , @abijames , @dpaun 
I have one branch I would like to merge and possibly get on to the live version. I hope to look at that tomorrow. Then i would be fine with experimental features going live.

**Comment by kprist** [comment]
@bwulff what is the current process for last minute deployments to production versus in experimental? there are some additional stuff I too would like to have on experimental but not on production. I was hoping I could make them on testing but that's out of the picture.

Could you create a release branch `r.12.x` or something for the production release and merge / tag stuff there as we did previously? I don't see such release branches lately so I assume you tag on master ?

**Pull request merged**
