### PR TITLE
Swik 409 implementing deckview components

### PR DESCRIPTION
**Pull request by vinaymodi**
Issue: SWIK-409

Please check the last 5 or 6 [comments on JIRA issue](https://slidewiki.atlassian.net/browse/SWIK-409)

Hard coded user id has been added for testing purposes. Pls see the comment for further explanation.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Ah, I was just about to merge, but it seems a conflict in services/deck.js was introduced today. Can you easily solve this?

**Comment by vinaymodi** [comment]
Try now

**Comment by kadevgraaf** [comment]
@bwulff can you review this PR? I get 2 errors that might be specific to mac os X when I build  (see below):

external_"tty":1 Uncaught ReferenceError: require is not defined(anonymous function) @ external_"tty":1(anonymous function) @ vendor.bundle.js:594__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ node.js:6(anonymous function) @ vendor.bundle.js:588__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ Fluxible.js:7(anonymous function) @ vendor.bundle.js:1814__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ index.js:5(anonymous function) @ vendor.bundle.js:1808__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ multi_vendor:8(anonymous function) @ vendor.bundle.js:569__webpack_require__ @ vendor.bundle.js:524(anonymous function) @ vendor.bundle.js:562(anonymous function) @ vendor.bundle.js:565

AND

external_"tty":1(anonymous function) @ vendor.bundle.js:594__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ node.js:6(anonymous function) @ vendor.bundle.js:588__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ Fluxible.js:7(anonymous function) @ vendor.bundle.js:1814__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ index.js:5(anonymous function) @ vendor.bundle.js:1808__webpack_require__ @ vendor.bundle.js:524fn @ vendor.bundle.js:49(anonymous function) @ multi_vendor:8(anonymous function) @ vendor.bundle.js:569__webpack_require__ @ vendor.bundle.js:524(anonymous function) @ vendor.bundle.js:562(anonymous function) @ vendor.bundle.js:565
main.js:1 Uncaught ReferenceError: exports is not defined(anonymous function) @ main.js:1

**Comment by vinaymodi** [comment]
Pls review and if useful merge it.

**Pull request merged**
