### PR TITLE
Show forked from info in deck view

### PR DESCRIPTION
**Pull request by stavmars**

### CODE REVIEW

**Comment by abijames** [comment]
@stavmars I am not seeing any information in the deckview when I fork a deck

**Comment by stavmars** [comment]
@abijames that's strange. I tried it again today multiple times and it works as expected. It diplays information about the fork origin under the creator.

**Comment by abijames** [comment]
I think this may be because of the branch tester docker container I use for testing. Could you message me a screenshot?

**Comment by stavmars** [comment]
forking_info_deck_view

**Comment by kadevgraaf** [comment]
Works nicely 👍

**Pull request merged**
