### PR TITLE
Swik 2289 add visualization for user edit

### PR DESCRIPTION
**Pull request by stavmars**
This PR concerns tasks [SWIK-2288](https://slidewiki.atlassian.net/browse/SWIK-2288), [SWIK-2457](https://slidewiki.atlassian.net/browse/SWIK-2457) and [SWIK-2289](https://slidewiki.atlassian.net/browse/SWIK-2289). A Learning Locker instance needs to be deployed for this to work (already deployed on experimental).

### CODE REVIEW

**Comment by stavmars** [comment]
@abijames I made most of the changes you recommended.

**Comment by abijames** [comment]
Testing for latest branch for accessibility.

On the chart:
* add h3 tags to the heading "Activity Timeline
* The div for the graph which contains the aria-descrbiedby tag needs
** aria-label="Data table for graph"
** tabindex="0"
* the div for the chart needs aira-hidden="true"

On the Popular tags section:
* remove colour for the tags (we can't manage the contrast)
* add h3 tags to the heading "popular tags"
* The div for the wordcloud which contains the aria-describedby tag needs:
** aria-label="Data table for popular tags"
** tabindex="0"
* the dic for the word cloud need aria-hidden="true"

**Comment by stavmars** [comment]
@abijames I addressed mopst of the points you raised (including the tag spacing in the popular tags). Re tag color, I used some darker color scheme to resolve the contrast issue. I'm afraid that using just a single color for the tags makes the tag cloud hard to read (not easy to distinguish similarly sized tags next to each other).

**Comment by abijames** [comment]
Hi @stavmars - thanks for the update, testing this now. Could you style the User Stats button on the my decks page the same as on the settings page - left justified and blue when on the user stats page?

**Comment by kprist** [comment]
I removed the button from the my decks page altogether, and at the same time present the stats page as part of the user settings pages

**Pull request merged**
