### PR TITLE
Swik 1645 replace search selection dropdowns

### PR DESCRIPTION
**Pull request by abijames**
Numerous accessibility improvements related to dropdown menus and form fields.

### CODE REVIEW

**Comment by abijames** [comment]
@kprist @kadevgraaf - this is a PR to fix accessibility issues on forms and dropdown menus. So it changes lots of pages but usually with the same functionality. If you have time, could someone quickly look through the code? I will check again for functionality. I would like to merge asap and possibly get on the live site too (@bwulff FYI).

**Comment by abijames** [comment]
I have tested this and would like to merge the branch asap. @kprist @kadevgraaf  if you have time could you quickly review the code?

**Comment by kadevgraaf** [comment]
Code looks good. Addition and usage of SWAutoComplete.js and SWDSDropdown.js seems most impactfull change. I have no testing environment though.
@kprist do you want to test it a bit more (Do we have time @abijames ?) or perhaps if you deploy it on the Athena server I can test from there?

**Comment by kprist** [comment]
@abijames @kadevgraaf I have deployed this branch to http://slidewiki.imsi.athenarc.gr/ if you want to test this.

**Pull request merged**
