### PR TITLE
Swik 754 prototype drag and drop slide reordering

### PR DESCRIPTION
**Pull request by stavmars**
This PR addresses addresses ticket SWIK-754 and adds:

- drag and drop in Decktree for deck/slide reordering using the existing deck tree react components

- It also adds 2 npm dependencies (react-dnd and react-dnd-html5-backend)

- @Sole-Valero also added some aria-labels and tooltips, though I temporarily removed the rename tooltips as it messed up the look of dragged nodes. 

This PR depends on changes to the deck service, that are already merged into master.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Seems to work like a charm on my localhost :)

I do get an error in console, but it might be unrelated - reordering still seems to work.
{ id: '209', stype: 'deck', sid: '209', spath: '', mode: 'view' }
{ id: '237', stype: 'deck', sid: '237', spath: '', mode: 'view' }
{ RequestError: Error: getaddrinfo ENOTFOUND deckservice.experimental.slidewiki.org deckservice.experimental.slidewiki.org:80
    at new RequestError (/Users/kadevgr/slidewiki-platform/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/kadevgr/slidewiki-platform/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/kadevgr/slidewiki-platform/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/kadevgr/slidewiki-platform/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/kadevgr/slidewiki-platform/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'RequestError',
  message: 'Error: getaddrinfo ENOTFOUND deckservice.experimental.slidewiki.org deckservice.experimental.slidewiki.org:80',
  cause: 
   { Error: getaddrinfo ENOTFOUND deckservice.experimental.slidewiki.org deckservice.experimental.slidewiki.org:80
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'deckservice.experimental.slidewiki.org',
     host: 'deckservice.experimental.slidewiki.org',
     port: 80 },
  error: 
   { Error: getaddrinfo ENOTFOUND deckservice.experimental.slidewiki.org deckservice.experimental.slidewiki.org:80
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'deckservice.experimental.slidewiki.org',
     host: 'deckservice.experimental.slidewiki.org',
     port: 80 },
  options: 
   { uri: 'http://deckservice.experimental.slidewiki.org/slide/1600-1',
     method: 'GET',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

**Comment by stavmars** [comment]
@kadevgraaf I don't get that error. Do you get this only when you move a tree node?

**Comment by kadevgraaf** [comment]
Hi @stavmars, I got the error at some point, but after I noticed the error it did not happen when I moved tree nodes, so it seems unrelated :)

**Comment by abijames** [comment]
I am getting some strange behaviour after reordering slides. The correct content is not always displayed in the View tab or sometimes I am getting "content not found". I will see if I can capture what is happening more accurately...

**Comment by abijames** [comment]
image

**Comment by stavmars** [comment]
@abijames I did not manage to reproduce this. Do you get wrong content or "content not found" even after you refresh the page?

**Comment by kadevgraaf** [comment]
merged for easier testing.

**Comment by kadevgraaf** [comment]
Hmm. Travis/CI/Build seems to fail.. Reverting for now

**Pull request merged**
