### PR TITLE
SWIK-2011. Button for iframe generation

### PR DESCRIPTION
**Pull request by vkovtun**
The fields in the popup window look too wide, but I did not want to deviate from the standard size of popups in the semantic-ui-react package.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Looks nice!
Perhaps the dimension of the embed could also have standard formats, e.g., "small", "medium", "large", "720p", etc.. or "Canvas standard".
@abijames  - should this also have a bit more information for users? (I think the average user needs some explaination,  "show this presentation in another system. For example in you learning management system (canvas, Blackboard), by adding the code below in the HTML source of a page you are editing in the learning management system/website".

**Comment by abijames** [comment]
There are quite a few design issues that need to still be resolved on this. I have added comments to https://slidewiki.atlassian.net/browse/SWIK-2011

**Comment by kadevgraaf** [comment]
I think it looks good. 
I am happy to merge this.
What do you think @abijames ?

Maybe it needs a bit of instructions/tooltip, e.g., "copy and past the HTML in (the HTML source) of your Web-based system (Wordpress site, Learning management system (Canvas, Blackboard), Webpage, et cetera)".

**Comment by abijames** [comment]
The embed dialog should have an option to select if you embed the deck (e.g. slidewiki.org/deck/####) or the slideshow (e.g. slidewiki.org/presentation/####/####).

If you are on a slide then you should be given the option to embed the deck to match the option provided by the other share options.

The iframe must have a title. This should be title="[SlideWiki deck on [deck title] by [creator]. See https://dequeuniversity.com/tips/provide-iframe-titles for further information on accessiblity of iframes

The dialog should have instructions: "Select from the options below and the copy the generate HTML into your site."

The modal window is not accessible. However as the share menu is also not accessible I am not going to worried about it for now!

**Comment by abijames** [comment]
@vkovtun please could you look at the comments I have made on this PR and let us know if you can resolve them. It would be nice to get this merged in this sprint (ending 7th)

**Comment by vkovtun** [comment]
@abijames yes I will start resolving the issues that you mentioned.

**Comment by vkovtun** [comment]
@abijames I implemented the changes you mentioned.

**Comment by abijames** [comment]
@vkovtun when I tried to test this branch the toolbar is duplicated and none of the buttons work 

image

**Comment by vkovtun** [comment]
@abijames I have fixed the issue with duplicated icons. Most likely it was a merging problem.

**Comment by abijames** [comment]
There are some layout and accessibility issues that need fixing:
image

* please left align the title  and change to "Embed Options"
* please can you make "Embed" and "Size" larger (or bold) so that they can be differentiated from the radio button labels. If you can't change the formatting then a colon after Embed and Size would help.
* Please add htmlFor and an id to link the radio field labels and input fields so that they are accessible for screen readers
* Please move id="embedModalDescription" to the div below the header "Select from,..". Also this should not be in <span> tags, can it be in <p>?
* Can you set focus to be on the first "Embed" option when the dialog loads?

**Comment by abijames** [comment]
I have just updated this branch and attempt to test it again but I can't load decks. @kadevgraaf  can you get it to work?

**Comment by kadevgraaf** [comment]
I get an error: "error: uncaughtException: this.getPresentationHref is not a function date=Thu Aug 09 2018 16:16:34 GMT+0200 (Central European Summer Time), pid=1578, uid=501, gid=20, cwd=/Users/kadevgr/slidewiki-platform, execPath=/usr/local/bin/node, version=v10.5.0, argv=[/usr/local/bin/node, /Users/kadevgr/slidewiki-platform/start.js], rss=221589504, heapTotal=157372416, heapUsed=138872048, external=142497, loadavg=[3.24365234375, 3.82568359375, 5.58349609375], uptime=1328
TypeError: this.getPresentationHref is not a function
    at ContentActionsFooter.render (/Users/kadevgr/slidewiki-platform/components/Deck/ContentPanel/ContentActions/ContentActionsFooter.js:138:45)
"
Can you fix this @vkovtun ?

**Comment by vkovtun** [comment]
I have fixed that error.

**Comment by abijames** [comment]
@vkovtun sorry more changes required:
Speaker notes are displaying on top of the modal (found on http://localhost:3000/deck/4349-1/test-import-preview/slide/36230-1/36230-1:2/view). This is also happening on the download modal but as this is not happening on experimental, I am worried your branch is introducing a bug (@kadevgraaf what do you think is causing this?)

On the modal
* Please change the modal heading to "Embed SlideWiki deck [deck title]". 
* Descriptive text needs correcting/improving "Use the options to select how this deck will be displayed. Then copy the generated code into your site."
* Give the descriptive text the id="embedModalDescription"
* On the text-area replace id="embedModalDescription" with aria-label="Embed content code"
* the width and height form labels are not associated with the input fields
* as before please can you increase the size of the "Embed" and Size" labels. 

Re the share menu:
* the icon used in the share icon is the used for another feature already. Can you change this to "share square"? it also seems larger than the other icons in the menu and doesn't seem to always appear. Looking at the code, you seem to have put the button in the component for the modal and not in the menu component. Perhaps that is the issue?
* can the embed option be at the end of the share menu after LinkedIn

**Comment by vkovtun** [comment]
@abijames I didn't see speaker notes being displayed on top of the modal. I checked your link too.

I have implemented the changes you requested.

I made a hack with the button, because adding custom buttons seems to be not supported by the library that provides those buttons. It only supports email and various social media.

**Comment by abijames** [comment]
@vkovtun are you continuing to work on this branch as you said there would be further updates. I have noticed the icon for Embed still need to change to  "share square" and the description "Use the options.... " is missing id="embedModalDescription"

Also when I tested the branch the deck tile does not appear in the dialog title (see screenshot)
image

**Comment by vkovtun** [comment]
@abijames I've pushed the fixes that you wanted. I just didn't understand: by missing ID you you mean the ID of the surrounding span tag?

**Comment by abijames** [comment]
@vkovtun line 228 of components/Deck/ContentPanel/ContentActions/EmbedModal.js  has
`FormattedMessage id='embedModal.description'` 
but the aria-describedby attribute on line 202 is 
`aria-describedby="embedModalDescription"`  
these ids need to be the same

**Comment by vkovtun** [comment]
@abijames I've fixed it.

**Comment by abijames** [comment]
I am happy for this branch to be merged but there are some conflicts that need to be resolved.

**Comment by vkovtun** [comment]
I've resolved the conflicts.

**Comment by abijames** [comment]
Thanks! @ali1k could you check this and merge it?

**Comment by ali1k** [comment]
sounds good IMO, thanks @vkovtun

**Pull request merged**
