### PR TITLE
Swik 134 presentation mode

### PR DESCRIPTION
**Pull request by huwf**
SWIK-134 is the presentation mode generally.  This PR will include the following tickets:
- SWIK-353/386 getting the data from the deckservice
- SWIK-387 play button
- SWIK-337 speaker notes (can be reached by pressing "s" in the presentation

It is currently hardcoded to a particular theme until SWIK-375 is complete

### CODE REVIEW

**Comment by kadevgraaf** [comment]
It works quite well with the original sample decks: 
http://localhost:3000/deck/7 and http://localhost:3000/deck/1
Also when adding a new deck from scratch (without upload)
Also speakernotes look really good.

When I go to presenter mode in an imported deck I however get an error in my browser (not in console/server/NPM):
**Error: Unable to find element with ID 147**.vendor.bundle.js%20line%20815%20%3E%20eval:38:15invariantwebpack:///./~/fbjs/lib/invariant.js?:38:15precacheChildNodeswebpack:///./~/react/lib/ReactDOMComponentTree.js?:97:44getNodeFromInstancewebpack:///./~/react/lib/ReactDOMComponentTree.js?:173:5SimpleEventPlugin.didPutListenerwebpack:///./~/react/lib/SimpleEventPlugin.js?:618:18EventPluginHub.putListenerwebpack:///./~/react/lib/EventPluginHub.js?:122:7putListenerwebpack:///./~/react/lib/ReactDOMComponent.js?:180:3.notifyAllwebpack:///./~/react/lib/CallbackQueue.js?:67:9ON_DOM_READY_QUEUEING.closewebpack:///./~/react/lib/ReactReconcileTransaction.js?:81:5Mixin.closeAllwebpack:///./~/react/lib/Transaction.js?:204:11Mixin.performwebpack:///./~/react/lib/Transaction.js?:151:11batchedMountComponentIntoNodewebpack:///./~/react/lib/ReactMount.js?:127:3Mixin.performwebpack:///./~/react/lib/Transaction.js?:138:13ReactDefaultBatchingStrategy.batchedUpdateswebpack:///./~/react/lib/ReactDefaultBatchingStrategy.js?:63:7batchedUpdateswebpack:///./~/react/lib/ReactUpdates.js?:98:3ReactMount._renderNewRootComponentwebpack:///./~/react/lib/ReactMount.js?:321:5ReactMount._renderSubtreeIntoContainerwebpack:///./~/react/lib/ReactMount.js?:402:21ReactMount.renderwebpack:///./~/react/lib/ReactMount.js?:423:12<anonymous>webpack:///./client.js?:43:5partiallyApplied/<webpack:///./~/setimmediate/setImmediate.js?:25:17runIfPresentwebpack:///./~/setimmediate/setImmediate.js?:44:21installPostMessageImplementation/onGlobalMessagewebpack:///./~/setimmediate/setImmediate.js?:90:17

I am not sure where this ID comes from. We did make some changes to the deck-service (e.g. w.r.t. getting speakernotes, but we fixed this, and since you merged from master, it should still work.) 
Can you take a look at this?

**Comment by Sole-Valero** [comment]
Please @kadevgraaf, can you share with us the slides you imported when you got that error  ?

**Comment by kadevgraaf** [comment]
[Got the Tech final with notes, Abi James ATEC.pptx](https://github.com/slidewiki/slidewiki-platform/files/485445/Got.the.Tech.final.with.notes.Abi.James.ATEC.pptx)

Also see See http://localhost:3000/deck/344-2/slide/1388-2/1388-2:1/view

**Comment by abijames** [comment]
A pptx with a single slide is available at https://drive.google.com/open?id=0B-oEnszZrEaMMDNtaHNOUE1SeUk

**Comment by kadevgraaf** [comment]
After research by Sole and Huw, it seems that the error is caused by the HTML syntax of the pptx2html import (above code works fine for non-imported (non pptx2html) decks/slides)
A possible cause could be the use of underscore, e.g., for _id and _idx, in the PPTX2HTML output HTML.

I propose to then merge this after we solve the current problem with the platform build on platform.manfredfris.ch

**Pull request merged**
