### PR TITLE
Swik-594 reset password

### PR DESCRIPTION
**Pull request by TBoonX**
Created a route /resetpassword
created view with store and actions
Added link to route in login modal "I can not access my account"

### CODE REVIEW

**Comment by ali1k** [comment]
the Error messages need to be improved for different cases (e.g. when the email does not exist) and needs to be connected to the mail server

**Comment by ali1k** [comment]
any updates on this pull request? does the mail server work now?
Can you also sync this branch with master?

**Comment by TBoonX** [comment]
Email sending not tested yet. Please wait.
Ben and I have to test it on the server before we merge it.

**Comment by ali1k** [comment]
will you be able to do the testing today? it also needs to be synced with master!
I think it is a nice needed feature to be in the first release

**Comment by ali1k** [comment]
The link to reset password seems to be broken even though I synced it with master!
See error:

`Uncaught TypeError: Cannot read property 'context' of nullhandleNoAccessClick @ LoginModal.js:131ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70executeDispatch @ EventPluginUtils.js:89executeDispatchesInOrder @ EventPluginUtils.js:112executeDispatchesAndRelease @ EventPluginHub.js:44executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:55forEachAccumulated @ forEachAccumulated.js:25processEventQueue @ EventPluginHub.js:231runEventQueueInBatch @ ReactEventEmitterMixin.js:18handleTopLevel @ ReactEventEmitterMixin.js:29handleTopLevelImpl @ ReactEventListener.js:73perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98dispatchEvent @ ReactEventListener.js:150`

**Comment by TBoonX** [comment]
Fixed - missed the bind(this) at handler bind. I dont know why this was not thrown last week on my system

**Comment by ali1k** [comment]
it sounds good enough for now. I will merge it now but should still work on it to fix the weird issue you mentioned.

**Pull request merged**
