### PR TITLE
SWIK 1500 fixUserMenu

### PR DESCRIPTION
**Pull request by kadevgraaf**

### CODE REVIEW

**Comment by abijames** [comment]
I've noticed a couple of issues that need to be fixed before release:
* icon for "My Notifications" on the menu is incorrect - it is currently the same as for My Settings
* dropdown icon and notifications on the menu button is in the wrong location, showing below the user image. Moving this to within the DIV containing the user images seem to fix this.
@Sole-Valero is on it....

**Comment by Sole-Valero** [comment]
Issue about icon of the notifications option solved, but I still have problems with the second issue.

**Comment by Sole-Valero** [comment]
Second Issue solved, thanks again @sednanref

**Comment by sednanref** [comment]
my pleasure :smile:

**Comment by abijames** [comment]
@sednanref @sole thank you for your hard work - this works well with screen readers in different browsers...

@kadevgraaf this can be merged!!!

**Pull request merged**
