### PR TITLE
SWIK-2037 add accessibility plugin to reveal.js

### PR DESCRIPTION
**Pull request by huwf**
Adds accessibility plugin to reveal.js.  Should be done with PR 15 of Reveal.js. @abijames

### CODE REVIEW

**Comment by abijames** [comment]
@kadevgraaf @ali1k could one of you review this code and merge if ok. I need to test if it will resolve a bug that BFW-Halle are reporting

**Comment by abijames** [comment]
unfortunately it looks like this update has introduced the feedback button into presentation mode again. Also I could REALLY go with aria-hidden="true" being placed on the platform header and footer in presentation mode

**Comment by kadevgraaf** [comment]
Hi @abijames  - I cannot see the feedback button in presentation mode on my localhost and on experimental.

**Comment by kadevgraaf** [comment]
Which selectors should we use to set aria-hidden="true" on?
Currently there are some aria-hidden already set in https://github.com/slidewiki/slidewiki-platform/blob/master/components/Deck/Presentation/Presentation.js#L40 :
```
            $('.ui.footer.sticky.segment').css({'display': 'none'});
            $('.ui.inverted.blue.menu, .ui.inverted.menu .blue.active.item').css({'display': 'none'});
            $('.ui.footer.sticky.segment').attr({'aria-hidden': 'hidden', 'hidden': 'hidden'});
            $('.ui.inverted.blue.menu, .ui.inverted.menu .blue.active.item').attr({'aria-hidden': 'hidden', 'hidden': 'hidden'});
            $('.ui.horizontal.segments.footer').css({'display': 'none'});
            $('.ui.vertical.footer').css({'display': 'none'});
            $('.ui.horizontal.segments.footer').attr({'aria-hidden': 'hidden', 'hidden': 'hidden'});
            $('.ui.vertical.footer').attr({'aria-hidden': 'hidden', 'hidden': 'hidden'});

```

I will add the aria-hidden="true" on the others as well in a new push.

**Comment by kadevgraaf** [comment]
New PR at https://github.com/slidewiki/slidewiki-platform/pull/761

**Pull request merged**
