### PR TITLE
Swik 835 create custom logger

### PR DESCRIPTION
**Pull request by vinaymodi**
I have added a custom logger which will allow to show console log messages in a better format with timestamps and also save in logs/<date>-platform.log file. This log will rotates everyday and if size is > 10MB any given day, new file will be created (i.e., rotating file).

Custom logger is extremely important in order to capture warnings and errors on stable and to keep track of debug, info and warning messages while developing (locally and experimental). I will give a demo of it in weekly dev call and if time permits I will also talk on how can we track errors etc across slidewiki infrastructure (distributed log tracking).

My strong opinion is that it should be merged into stable as soon as possible so that we can ask (developers, those who run separate installation) partners to share this log file (of a particular day or days) in case they face any issues in using slidewiki.

To try this locally, do not forget to use 'npm install'. You may see two warnings but they can be safely ignored. I can explain about it separately if you need to know.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Looks good. Very informative logs. I do get the following warning:
./~/winston/~/colors/lib/colors.js
Critical dependencies:
127:29-43 the request of a dependency is an expression
 @ ./~/winston/~/colors/lib/colors.js 127:29-43
warnings @ client:68
sock.onmessage @ socket.js:37
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
SockJS._transportMessage @ main.js:272
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
client:68 ./~/winston/~/colors/lib/extendStringPrototype.js
Critical dependencies:
106:31-45 the request of a dependency is an expression
 @ ./~/winston/~/colors/lib/extendStringPrototype.js 106:31-45

**Comment by vinaymodi** [comment]
This is ready for merge. Custom logger works fine with rest of the site (i.e. MediaQuery and onClick events work fine). Added support for distributed tracking. It is up-to us to use it or not but feature has been made available.

**Comment by kosh** [comment]
This is ready for QA. Please also try when microservice is down to check it works fine on service errors.

**Comment by kosh** [comment]
It is possible to send local log messages to remote Fluent server. This should not be an issue as the logging library has support for this out of the box.

**Comment by vinaymodi** [comment]
Made changes after reading testing feedback. In my opinion, this is good for merge.

**Pull request merged**
