### PR TITLE
SWIK-1031 deck edit rights for april

### PR DESCRIPTION
**Pull request by TBoonX**
Many changes by Kostis, Stavros and me.
In general the Deck Edit View and the permission handling changed/was created.
There are new actions, stores and services.
Additionally a few unhandled promises were fixed.

Work of deck edit rights and new forking mechanism is part of this PR.

### CODE REVIEW

**Comment by kadevgraaf** [comment]
Thanks!  Looks nice. I went for testing and came across a challenge:
When I want to edit one of my decks in the 'my decks' overview, it says "_No Edit Rights
You can only view this deck. To make changes, you may ask the owner to grant you edit rights or fork the deck. Forking a deck means creating your copy of the deck._". After you fork it, the forked deck correctly shows up in the 'my decks' overview but I still cannot edit the forked deck, or the original. It shows the same user (myself) as being the owner of the deck.

Also when I try to edit someone else his/her deck, it is the same: after forking I still cannot edit the deck or slides.

Perhaps this is due to my specific account (I had problems before with the 'my decks' overview)

Adding people to groups works well - If I add another account of myself to a group, then I can see this group when I am signed in into the other account. I cannot test if I can edit decks due to above reason.

**Comment by kprist** [comment]
@kadevgraaf this seems strange, but the issues with specific accounts in "my decks" where due to data on experimental. What setup are you using for testing this? Do you use a data dump from experimental for instance?

**Comment by kadevgraaf** [comment]
Hi @kprist !
I am using the experimental microservices.
I tested with users kadegraaf and kadevgraaf on decks 1147 (forked to 1162 and 1164-1167) and 1090, forked to 1168)

I also tried with your deck 54-1 - forked to 1178-1, but in the forked deck I still get the dialog and cannot edit, even though I am listed as the owner and creator in deck view.

**Comment by kprist** [comment]
I am sorry, should have been more explicit about this. There are two issues in QA, https://slidewiki.atlassian.net/browse/SWIK-1030 and https://slidewiki.atlassian.net/browse/SWIK-1031. The deck service on experimental is not compatible with the PR for the platform, you should check out SWIK-1030 branch in deck service and run it locally.

**Comment by kadevgraaf** [comment]
Aah of course. Sorry,  I assumed 1030 was merged already. Will test using 1030 local as well 👍 
My earlier comments can be disregarded then.

**Comment by kprist** [comment]
We didn't want to merge the deck service part because it would break current platform. Feel free to merge the deck-service PR https://github.com/slidewiki/deck-service/pull/73 after you decide we can merge this one.

**Pull request merged**
