### PR TITLE
Swik 2245 fix dragging large images

### PR DESCRIPTION
**Pull request by aoelen**
Max-width property is added to newly inserted images

### CODE REVIEW

**Comment by abijames** [comment]
This fixes the bug although the images are now imported at a very small size. @kadevgraaf if you are happy with this approach then I am ok for this to be merged.

**Comment by aoelen** [comment]
The initial width of the images is set to 30% of the slide width. This can be changed to, for example, 50% if you think that is better.

**Comment by abijames** [comment]
50% would be better.

Sent from my iPhone

On 17 Oct 2018, at 12:58, aoelen <notifications@github.com<mailto:notifications@github.com>> wrote:


The initial width of the images is set to 30% of the slide width. This can be changed to, for example, 50% if you think that is better.

**Comment by aoelen** [comment]
Okay, just pushed the change

**Comment by kadevgraaf** [comment]
Code looks good and works wel in FF and Chrome. Thanks! 👍

**Pull request merged**
