### PR TITLE
SWIK-838 accesible labels decktree

### PR DESCRIPTION
**Pull request by Sole-Valero**
aria-label and data-tooltip atributtes added to the button of the TreePanel toolbar (at TreePanel.js)

### CODE REVIEW

**Comment by abijames** [comment]
Hi @Sole-Valero I have been testing the branches and the aria-labels are not coming through to the DOM. I was wondering if that is because the component TreePanel.js (slidewiki-platform/components/Deck/TreePanel/TreePanel.js) is overwriting your code.

**Comment by Sole-Valero** [comment]
Some screenshots added to:

https://slidewiki.atlassian.net/browse/SWIK-838

@abijames, I can see the aria-labels when I inspect...

**Comment by abijames** [comment]
This is ok to merge now

**Comment by Sole-Valero** [comment]
I'm going to close this pull request, because it can be dangerous to merge it now. @Stavros as work on the same components, so we have decide to move my code to his branch SWIK-754-Prototype-drag-and-drop-slide-reordering

**Pull request closed without merging**
